export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS"
export const GET_ALL_PRODUCTS_CATEGORY = "GET_ALL_PRODUCTS_CATEGORY"
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS"
export const ADD_PRODUCT = "ADD_PRODUCT"
export const EDIT_PRODUCT = "EDIT_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT"

export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES"


export const AUTH_USER = "AUTH_USER"
export const GET_AUTH = "GET_AUTH"